-- ============================================================
-- TechStore Database Schema - PostgreSQL
-- De tai: Website ban do cong nghe
-- Backend: Java Spring Boot
-- Version: 2.0 - Complete schema for thesis scope
-- Ghi chu: File nay dung de tao lai database trong moi truong dev.
-- ============================================================

BEGIN;

-- ============================================================
-- Drop tables for re-run in development
-- ============================================================

DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS chat_sessions CASCADE;
DROP TABLE IF EXISTS contact_messages CASCADE;
DROP TABLE IF EXISTS faqs CASCADE;
DROP TABLE IF EXISTS news_posts CASCADE;
DROP TABLE IF EXISTS banners CASCADE;
DROP TABLE IF EXISTS product_reviews CASCADE;
DROP TABLE IF EXISTS coupon_usages CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS coupons CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS product_specifications CASCADE;
DROP TABLE IF EXISTS specification_keys CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS product_variants CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS brands CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS password_reset_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS set_updated_at() CASCADE;

-- ============================================================
-- Function: automatically update updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 1. USERS
-- Luu khach hang, nhan vien, quan tri vien trong cung mot bang.
-- Phan quyen bang cot role de don gian cho pham vi luan van.
-- ============================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,

    role VARCHAR(30) NOT NULL DEFAULT 'ROLE_CUSTOMER',
    phone VARCHAR(20),
    gender VARCHAR(10),
    date_of_birth DATE,
    address TEXT,
    avatar TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT chk_users_role
        CHECK (role IN ('ROLE_CUSTOMER', 'ROLE_STAFF', 'ROLE_ADMIN')),

    CONSTRAINT chk_users_gender
        CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'OTHER')),

    CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'BLOCKED'))
);

COMMENT ON TABLE users IS 'Luu tai khoan khach hang, nhan vien va quan tri vien';
COMMENT ON COLUMN users.role IS 'ROLE_CUSTOMER, ROLE_STAFF, ROLE_ADMIN';
COMMENT ON COLUMN users.status IS 'ACTIVE, BLOCKED';

-- ============================================================
-- 2. PASSWORD RESET TOKENS
-- Phuc vu chuc nang quen mat khau.
-- ============================================================

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    expired_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE password_reset_tokens IS 'Luu token dat lai mat khau, co thoi han va chi duoc dung mot lan';

-- ============================================================
-- 3. CATEGORIES
-- Ho tro danh muc cha - con.
-- ============================================================

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    parent_id BIGINT,

    description TEXT,
    image_url TEXT,
    sort_order INT NOT NULL DEFAULT 0,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT uq_categories_slug UNIQUE (slug),

    CONSTRAINT chk_categories_sort_order
        CHECK (sort_order >= 0),

    CONSTRAINT chk_categories_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id)
        REFERENCES categories(id)
        ON DELETE SET NULL
);

COMMENT ON TABLE categories IS 'Luu danh muc san pham, co the co danh muc cha';

-- ============================================================
-- 4. BRANDS
-- Thuong hieu/hang san xuat.
-- ============================================================

CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL,

    logo_url TEXT,
    description TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT uq_brands_slug UNIQUE (slug),

    CONSTRAINT chk_brands_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

COMMENT ON TABLE brands IS 'Luu thong tin thuong hieu san pham';

-- ============================================================
-- 5. PRODUCTS
-- Thong tin chung cua san pham. Gia va ton kho nam o product_variants.
-- ============================================================

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_id BIGINT NOT NULL,
    brand_id BIGINT,

    name VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL,
    description TEXT,

    featured BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT uq_products_slug UNIQUE (slug),

    CONSTRAINT chk_products_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_products_brand
        FOREIGN KEY (brand_id)
        REFERENCES brands(id)
        ON DELETE SET NULL
);

COMMENT ON TABLE products IS 'Luu thong tin chung cua san pham';
COMMENT ON COLUMN products.featured IS 'Danh dau san pham noi bat de hien thi tren trang chu';

-- ============================================================
-- 6. PRODUCT VARIANTS
-- Moi bien the co SKU, gia, gia khuyen mai va ton kho rieng.
-- ============================================================

CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL,

    name VARCHAR(150) NOT NULL,
    sku VARCHAR(100) NOT NULL,

    price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    sale_price NUMERIC(12, 2),
    sale_start_at TIMESTAMP,
    sale_end_at TIMESTAMP,

    stock INT NOT NULL DEFAULT 0,
    thumbnail_url TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT uq_product_variants_sku UNIQUE (sku),

    CONSTRAINT chk_product_variants_price
        CHECK (price >= 0),

    CONSTRAINT chk_product_variants_sale_price
        CHECK (sale_price IS NULL OR sale_price >= 0),

    CONSTRAINT chk_product_variants_sale_price_lte_price
        CHECK (sale_price IS NULL OR sale_price <= price),

    CONSTRAINT chk_product_variants_sale_date
        CHECK (sale_start_at IS NULL OR sale_end_at IS NULL OR sale_end_at >= sale_start_at),

    CONSTRAINT chk_product_variants_stock
        CHECK (stock >= 0),

    CONSTRAINT chk_product_variants_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    CONSTRAINT fk_product_variants_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE product_variants IS 'Luu cac phien ban cu the cua san pham, co SKU, gia va ton kho rieng';
COMMENT ON COLUMN product_variants.sale_price IS 'Gia khuyen mai cua bien the, neu co';

-- ============================================================
-- 7. PRODUCT IMAGES
-- variant_id co the NULL neu anh dung chung cho san pham.
-- ============================================================

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL,
    variant_id BIGINT,

    image_url TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT chk_product_images_sort_order
        CHECK (sort_order >= 0),

    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_product_images_variant
        FOREIGN KEY (variant_id)
        REFERENCES product_variants(id)
        ON DELETE SET NULL
);

COMMENT ON TABLE product_images IS 'Luu anh san pham; variant_id co the NULL neu anh dung chung cho san pham';

-- ============================================================
-- 8. SPECIFICATION KEYS
-- Ten thong so ky thuat theo tung danh muc.
-- ============================================================

CREATE TABLE specification_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_id BIGINT NOT NULL,

    name VARCHAR(100) NOT NULL,
    unit VARCHAR(50),
    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT chk_specification_keys_sort_order
        CHECK (sort_order >= 0),

    CONSTRAINT uq_specification_keys_category_name
        UNIQUE (category_id, name),

    CONSTRAINT fk_specification_keys_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE specification_keys IS 'Luu ten cac thong so ky thuat theo danh muc san pham';

-- ============================================================
-- 9. PRODUCT SPECIFICATIONS
-- Gia tri thong so cua tung san pham.
-- ============================================================

CREATE TABLE product_specifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL,
    specification_key_id BIGINT NOT NULL,

    value VARCHAR(255) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT uq_product_specifications_product_key
        UNIQUE (product_id, specification_key_id),

    CONSTRAINT fk_product_specifications_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_product_specifications_key
        FOREIGN KEY (specification_key_id)
        REFERENCES specification_keys(id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE product_specifications IS 'Luu gia tri thong so ky thuat cua tung san pham';

-- ============================================================
-- 10. CARTS
-- Moi user co mot gio hang hien tai.
-- ============================================================

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_carts_user UNIQUE (user_id),

    CONSTRAINT fk_carts_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE carts IS 'Luu gio hang hien tai cua nguoi dung';

-- ============================================================
-- 11. CART ITEMS
-- UNIQUE(cart_id, product_variant_id) giup tranh trung san pham trong gio.
-- ============================================================

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cart_id BIGINT NOT NULL,
    product_variant_id BIGINT NOT NULL,

    quantity INT NOT NULL DEFAULT 1,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_cart_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT uq_cart_items_cart_variant
        UNIQUE (cart_id, product_variant_id),

    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id)
        REFERENCES carts(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_cart_items_product_variant
        FOREIGN KEY (product_variant_id)
        REFERENCES product_variants(id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE cart_items IS 'Luu cac san pham trong gio hang';

-- ============================================================
-- 12. COUPONS
-- Ma giam gia: PERCENTAGE hoac FIXED.
-- ============================================================

CREATE TABLE coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,

    discount_type VARCHAR(20) NOT NULL,
    discount_value NUMERIC(12, 2) NOT NULL,

    min_order_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    max_discount_amount NUMERIC(12, 2),

    usage_limit INT,
    used_count INT NOT NULL DEFAULT 0,

    start_at TIMESTAMP,
    end_at TIMESTAMP,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT chk_coupons_discount_type
        CHECK (discount_type IN ('PERCENTAGE', 'FIXED')),

    CONSTRAINT chk_coupons_discount_value
        CHECK (
            (discount_type = 'PERCENTAGE' AND discount_value > 0 AND discount_value <= 100)
            OR
            (discount_type = 'FIXED' AND discount_value > 0)
        ),

    CONSTRAINT chk_coupons_min_order_amount
        CHECK (min_order_amount >= 0),

    CONSTRAINT chk_coupons_max_discount_amount
        CHECK (max_discount_amount IS NULL OR max_discount_amount >= 0),

    CONSTRAINT chk_coupons_usage_limit
        CHECK (usage_limit IS NULL OR usage_limit >= 0),

    CONSTRAINT chk_coupons_used_count
        CHECK (used_count >= 0),

    CONSTRAINT chk_coupons_used_count_limit
        CHECK (usage_limit IS NULL OR used_count <= usage_limit),

    CONSTRAINT chk_coupons_date_range
        CHECK (start_at IS NULL OR end_at IS NULL OR end_at >= start_at),

    CONSTRAINT chk_coupons_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'EXPIRED'))
);

COMMENT ON TABLE coupons IS 'Luu thong tin ma giam gia';
COMMENT ON COLUMN coupons.discount_type IS 'PERCENTAGE, FIXED';

-- ============================================================
-- 13. ORDERS
-- Luu thong tin tong quat cua don hang.
-- Payment duoc tach sang bang payments.
-- ============================================================

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    coupon_id BIGINT,
    coupon_code VARCHAR(50),

    order_code VARCHAR(50) NOT NULL,

    subtotal_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    shipping_fee NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    final_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,

    order_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    receiver_name VARCHAR(100) NOT NULL,
    receiver_phone VARCHAR(20) NOT NULL,
    shipping_address TEXT NOT NULL,

    note TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT uq_orders_order_code UNIQUE (order_code),

    CONSTRAINT chk_orders_subtotal_amount
        CHECK (subtotal_amount >= 0),

    CONSTRAINT chk_orders_shipping_fee
        CHECK (shipping_fee >= 0),

    CONSTRAINT chk_orders_discount_amount
        CHECK (discount_amount >= 0),

    CONSTRAINT chk_orders_final_amount
        CHECK (final_amount >= 0),

    CONSTRAINT chk_orders_order_status
        CHECK (order_status IN ('PENDING', 'CONFIRMED', 'SHIPPING', 'COMPLETED', 'CANCELLED')),

    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_orders_coupon
        FOREIGN KEY (coupon_id)
        REFERENCES coupons(id)
        ON DELETE SET NULL
);

COMMENT ON TABLE orders IS 'Luu thong tin don hang';
COMMENT ON COLUMN orders.subtotal_amount IS 'Tong tien hang truoc giam gia va phi van chuyen';
COMMENT ON COLUMN orders.final_amount IS 'So tien khach can thanh toan sau giam gia va phi van chuyen';
COMMENT ON COLUMN orders.order_status IS 'PENDING, CONFIRMED, SHIPPING, COMPLETED, CANCELLED';

-- ============================================================
-- 14. ORDER ITEMS
-- Luu snapshot san pham tai thoi diem mua.
-- ============================================================

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_variant_id BIGINT NOT NULL,

    product_name VARCHAR(200) NOT NULL,
    variant_name VARCHAR(150) NOT NULL,
    product_sku VARCHAR(100),

    price NUMERIC(12, 2) NOT NULL,
    quantity INT NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_order_items_price
        CHECK (price >= 0),

    CONSTRAINT chk_order_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_order_items_total_price
        CHECK (total_price >= 0),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_order_items_product_variant
        FOREIGN KEY (product_variant_id)
        REFERENCES product_variants(id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE order_items IS 'Luu chi tiet san pham trong don hang va snapshot ten, gia tai thoi diem mua';

-- ============================================================
-- 15. PAYMENTS
-- Thanh toan gia lap: COD hoac MOCK_BANKING.
-- ============================================================

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,

    method VARCHAR(30) NOT NULL DEFAULT 'COD',
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    transaction_code VARCHAR(100),

    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_payments_order UNIQUE (order_id),

    CONSTRAINT chk_payments_method
        CHECK (method IN ('COD', 'MOCK_BANKING')),

    CONSTRAINT chk_payments_status
        CHECK (status IN ('PENDING', 'PAID', 'FAILED')),

    CONSTRAINT chk_payments_amount
        CHECK (amount >= 0),

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE payments IS 'Luu thong tin thanh toan cua don hang';
COMMENT ON COLUMN payments.method IS 'COD, MOCK_BANKING';
COMMENT ON COLUMN payments.status IS 'PENDING, PAID, FAILED';

-- ============================================================
-- 16. COUPON USAGES
-- Luu lich su su dung ma giam gia.
-- ============================================================

CREATE TABLE coupon_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    coupon_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,

    used_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_coupon_usages_order UNIQUE (order_id),

    CONSTRAINT fk_coupon_usages_coupon
        FOREIGN KEY (coupon_id)
        REFERENCES coupons(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_coupon_usages_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_coupon_usages_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE coupon_usages IS 'Luu user nao da su dung coupon nao cho don hang nao';

-- ============================================================
-- 17. PRODUCT REVIEWS
-- Chi danh gia sau khi mua hang. Dieu kien don hang COMPLETED kiem tra o Service.
-- ============================================================

CREATE TABLE product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,

    rating INT NOT NULL,
    comment TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'VISIBLE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT uq_product_reviews_order_item UNIQUE (order_item_id),
    CONSTRAINT uq_product_reviews_user_product UNIQUE (user_id, product_id),

    CONSTRAINT chk_product_reviews_rating
        CHECK (rating BETWEEN 1 AND 5),

    CONSTRAINT chk_product_reviews_status
        CHECK (status IN ('VISIBLE', 'HIDDEN', 'PENDING')),

    CONSTRAINT fk_product_reviews_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_product_reviews_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_product_reviews_order_item
        FOREIGN KEY (order_item_id)
        REFERENCES order_items(id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE product_reviews IS 'Luu danh gia va binh luan san pham';
COMMENT ON COLUMN product_reviews.rating IS 'Gia tri tu 1 den 5';
COMMENT ON COLUMN product_reviews.status IS 'VISIBLE, HIDDEN, PENDING';

-- ============================================================
-- 18. BANNERS
-- Banner trang chu va trang san pham.
-- ============================================================

CREATE TABLE banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(150) NOT NULL,
    image_url TEXT NOT NULL,
    link_url TEXT,

    position VARCHAR(50),
    sort_order INT NOT NULL DEFAULT 0,

    start_at TIMESTAMP,
    end_at TIMESTAMP,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT chk_banners_position
        CHECK (position IS NULL OR position IN ('HOME_TOP', 'HOME_MIDDLE', 'HOME_BOTTOM', 'PRODUCT_PAGE')),

    CONSTRAINT chk_banners_sort_order
        CHECK (sort_order >= 0),

    CONSTRAINT chk_banners_date_range
        CHECK (start_at IS NULL OR end_at IS NULL OR end_at >= start_at),

    CONSTRAINT chk_banners_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

COMMENT ON TABLE banners IS 'Luu banner hien thi tren website';

-- ============================================================
-- 19. NEWS POSTS
-- Tin tuc, bai viet, noi dung quan tri.
-- ============================================================

CREATE TABLE news_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    summary TEXT,
    content TEXT,
    thumbnail_url TEXT,

    author_id BIGINT,

    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT uq_news_posts_slug UNIQUE (slug),

    CONSTRAINT chk_news_posts_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'HIDDEN')),

    CONSTRAINT fk_news_posts_author
        FOREIGN KEY (author_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

COMMENT ON TABLE news_posts IS 'Luu tin tuc va bai viet noi dung cua website';

-- ============================================================
-- 20. FAQS
-- Cau hoi thuong gap.
-- ============================================================

CREATE TABLE faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    question VARCHAR(500) NOT NULL,
    answer TEXT NOT NULL,

    sort_order INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT chk_faqs_sort_order
        CHECK (sort_order >= 0),

    CONSTRAINT chk_faqs_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

COMMENT ON TABLE faqs IS 'Luu danh sach cau hoi thuong gap';

-- ============================================================
-- 21. CONTACT MESSAGES
-- Form lien he cua khach hang.
-- ============================================================

CREATE TABLE contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20),

    subject VARCHAR(255),
    message TEXT NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'NEW',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_contact_messages_status
        CHECK (status IN ('NEW', 'PROCESSING', 'RESOLVED'))
);

COMMENT ON TABLE contact_messages IS 'Luu thong tin khach hang gui qua form lien he';

-- ============================================================
-- 22. CHAT SESSIONS
-- Chat ho tro dang REST API, chua bat buoc realtime WebSocket.
-- ============================================================

CREATE TABLE chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id BIGINT NOT NULL,
    staff_id BIGINT,

    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,

    CONSTRAINT chk_chat_sessions_status
        CHECK (status IN ('OPEN', 'CLOSED')),

    CONSTRAINT fk_chat_sessions_customer
        FOREIGN KEY (customer_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_chat_sessions_staff
        FOREIGN KEY (staff_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

COMMENT ON TABLE chat_sessions IS 'Luu phien chat ho tro giua khach hang va nhan vien';

-- ============================================================
-- 23. CHAT MESSAGES
-- Tin nhan trong phien chat.
-- ============================================================

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    session_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,

    message TEXT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_chat_messages_session
        FOREIGN KEY (session_id)
        REFERENCES chat_sessions(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_chat_messages_sender
        FOREIGN KEY (sender_id)
        REFERENCES users(id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE chat_messages IS 'Luu tin nhan trong tung phien chat';

-- ============================================================
-- INDEXES
-- ============================================================

-- Users
CREATE UNIQUE INDEX uq_users_email_lower ON users (LOWER(email));
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_status ON users(status);

-- Password reset tokens
CREATE UNIQUE INDEX uq_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
CREATE INDEX idx_password_reset_tokens_expired_at ON password_reset_tokens(expired_at);

-- Categories
CREATE INDEX idx_categories_parent_id ON categories(parent_id);
CREATE INDEX idx_categories_status ON categories(status);
CREATE INDEX idx_categories_sort_order ON categories(sort_order);

-- Brands
CREATE INDEX idx_brands_status ON brands(status);

-- Products
CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_products_brand_id ON products(brand_id);
CREATE INDEX idx_products_status ON products(status);
CREATE INDEX idx_products_featured ON products(featured);
CREATE INDEX idx_products_name_lower ON products(LOWER(name));
CREATE INDEX idx_products_filter ON products(status, category_id, brand_id, featured);

-- Product variants
CREATE INDEX idx_product_variants_product_id ON product_variants(product_id);
CREATE INDEX idx_product_variants_status ON product_variants(status);
CREATE INDEX idx_product_variants_price ON product_variants(price);
CREATE INDEX idx_product_variants_sale_price ON product_variants(sale_price);

-- Product images
CREATE INDEX idx_product_images_product_id ON product_images(product_id);
CREATE INDEX idx_product_images_variant_id ON product_images(variant_id);

-- Specification keys
CREATE INDEX idx_specification_keys_category_id ON specification_keys(category_id);
CREATE INDEX idx_specification_keys_sort_order ON specification_keys(sort_order);

-- Product specifications
CREATE INDEX idx_product_specifications_product_id ON product_specifications(product_id);
CREATE INDEX idx_product_specifications_key_id ON product_specifications(specification_key_id);

-- Carts and cart items
CREATE INDEX idx_cart_items_cart_id ON cart_items(cart_id);
CREATE INDEX idx_cart_items_product_variant_id ON cart_items(product_variant_id);

-- Coupons
CREATE UNIQUE INDEX uq_coupons_code_upper ON coupons(UPPER(code));
CREATE INDEX idx_coupons_status ON coupons(status);
CREATE INDEX idx_coupons_date_range ON coupons(start_at, end_at);

-- Orders
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_coupon_id ON orders(coupon_id);
CREATE INDEX idx_orders_order_status ON orders(order_status);
CREATE INDEX idx_orders_created_at ON orders(created_at);

-- Order items
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);
CREATE INDEX idx_order_items_product_variant_id ON order_items(product_variant_id);

-- Payments
CREATE INDEX idx_payments_status ON payments(status);
CREATE INDEX idx_payments_method ON payments(method);

-- Coupon usages
CREATE INDEX idx_coupon_usages_coupon_id ON coupon_usages(coupon_id);
CREATE INDEX idx_coupon_usages_user_id ON coupon_usages(user_id);

-- Product reviews
CREATE INDEX idx_product_reviews_user_id ON product_reviews(user_id);
CREATE INDEX idx_product_reviews_product_id ON product_reviews(product_id);
CREATE INDEX idx_product_reviews_status ON product_reviews(status);

-- Banners
CREATE INDEX idx_banners_status ON banners(status);
CREATE INDEX idx_banners_position ON banners(position);
CREATE INDEX idx_banners_sort_order ON banners(sort_order);

-- News posts
CREATE INDEX idx_news_posts_author_id ON news_posts(author_id);
CREATE INDEX idx_news_posts_status ON news_posts(status);
CREATE INDEX idx_news_posts_created_at ON news_posts(created_at);

-- FAQs
CREATE INDEX idx_faqs_status ON faqs(status);
CREATE INDEX idx_faqs_sort_order ON faqs(sort_order);

-- Contact messages
CREATE INDEX idx_contact_messages_status ON contact_messages(status);
CREATE INDEX idx_contact_messages_created_at ON contact_messages(created_at);

-- Chat
CREATE INDEX idx_chat_sessions_customer_id ON chat_sessions(customer_id);
CREATE INDEX idx_chat_sessions_staff_id ON chat_sessions(staff_id);
CREATE INDEX idx_chat_sessions_status ON chat_sessions(status);
CREATE INDEX idx_chat_messages_session_id ON chat_messages(session_id);
CREATE INDEX idx_chat_messages_sender_id ON chat_messages(sender_id);
CREATE INDEX idx_chat_messages_created_at ON chat_messages(created_at);

-- ============================================================
-- TRIGGERS FOR updated_at
-- ============================================================

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_categories_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_brands_updated_at
BEFORE UPDATE ON brands
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_product_variants_updated_at
BEFORE UPDATE ON product_variants
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_specification_keys_updated_at
BEFORE UPDATE ON specification_keys
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_product_specifications_updated_at
BEFORE UPDATE ON product_specifications
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_carts_updated_at
BEFORE UPDATE ON carts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_cart_items_updated_at
BEFORE UPDATE ON cart_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_coupons_updated_at
BEFORE UPDATE ON coupons
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_payments_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_product_reviews_updated_at
BEFORE UPDATE ON product_reviews
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_banners_updated_at
BEFORE UPDATE ON banners
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_news_posts_updated_at
BEFORE UPDATE ON news_posts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_faqs_updated_at
BEFORE UPDATE ON faqs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_contact_messages_updated_at
BEFORE UPDATE ON contact_messages
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_chat_sessions_updated_at
BEFORE UPDATE ON chat_sessions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
