server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/techstore
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:techstore_super_secret_key_2026_for_graduation_project}
app.jwt.expiration-ms=86400000